body:
  - type: dropdown
    attributes:
      name: decimal_places
      label: Decimal Places
      description: Number of decimal places to round hours to (0-6)
      defaultValue: 2
      options:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
